name:                 kripke-checker
version:              0.1.0.0
visibility:           public
id:                   kripke-checker-0.1.0.0-inplace
key:                  kripke-checker-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      Kripke.Checker Kripke.Types
import-dirs:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/build

library-dirs:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/build

library-dirs-static:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/build

dynamic-library-dirs:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/build

data-dir:             /home/oran/Projects/Kripke/kripke-app/haskell/.
hs-libraries:         HSkripke-checker-0.1.0.0-inplace
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/doc/html/kripke-checker/kripke-checker.haddock

haddock-html:
    /home/oran/Projects/Kripke/kripke-app/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kripke-checker-0.1.0.0/doc/html/kripke-checker
